from crewai.flow.flow import Flow, listen, start
from crewai import Agent
from dotenv import load_dotenv
from litellm import completion

import pm4py
import pandas

load_dotenv()

class pmAnalytics(Flow):

    counterTry = 0 ## number shows the number of try of analytical agent
    MAXIMAL_TRY = 2 ## number of maximal try to reproduce the code

    userQuery = input("Enter the desired Process Mining query: ")

    eventLogPath = r"ENTER HERE THE FILE PATH!"
    
    fileFormat = "" ##it is needed for analytical agent


    @start()
    def dataPrep(self): ##no LLM, just deterministic
        
        if(self.eventLogPath.endswith (".csv")) : ## if data in csv format
             self.fileFormat = "CSV"
             print("CSV ENTERED!")
             db = pandas.read_csv(self.eventLogPath)
        elif(self.eventLogPath.endswith (".xes")) : ## if data in xes format
             self.fileFormat = "XES"
             xesRead = pm4py.read_xes(self.eventLogPath)
             db = pm4py.convert_to_dataframe(xesRead)
        else:
            raise SystemExit("The fileformat is not supported!")
        
        
        numberOfRows = len(db) ## number of rows
        namesColumns = list(db.columns)  ## names of columns
        typesColumns = db.dtypes ## types of columns
        numberOfColumns = len(db.columns) ## number of columns

        metaDataDict = {"numberRows" : numberOfRows, 
                    "namesColumns" :namesColumns,
                    "typesColumns" : typesColumns,
                    "numberColumns" : numberOfColumns
                        }
        
        self.state["metaData"] = metaDataDict ##needed for analytical and judge agent

        print(metaDataDict)
        return metaDataDict
    

   
    @listen(dataPrep)
    def analyse(self): #Agent with LLM
       
        while True:

            analyst = Agent(
                role="Analytical Agent",
                goal= f"Return Python code without introducing it as a variable for the required analyse \
                based on the user query: {self.userQuery} and profiled dataset: {self.state["metaData"]}",
                backstory="You are the analystics that creates the code for the required analyse." \
                f"The given event log is available in a variable called 'data' as a string and in dataformat: '{self.fileFormat}'. " \
                "Moreover, save the final part in 'execResults' variable which is needed for the answering query",
                verbose=True
                )

            generatedCode = analyst.kickoff(f"Create a executable code for the {self.userQuery} and {self.state["metaData"]}")

            self.counterTry+=1

            if (self.check(generatedCode)) : ## if the generated code is approved
                break

            elif (self.counterTry == self.MAXIMAL_TRY):
                 raise SystemExit("The analyst agent generated incorrect code more than the maximum number of times.")


        self.state["analyseResult"] = generatedCode ## needed for judge, executor agent
        



    def check(self, code): ## helper function (judge Agent) for checking the generated code by an LLM
         
        judge = Agent(
            role="Judge Agent",
            goal= f"Return the value 'true' if you think that generated code {code} is appropriate for the \
            {self.state["metaData"]} to answer the question: {self.userQuery} and return 'false' otherwise. " ,
            backstory="You are the judge agent that will evaluate " \
            "whether the code generated by the analytical agent is good enough and return true or false.",
            verbose=True
            )

        approve = judge.kickoff(f"Return the boolean value true if this code :{code} is \
        good for answering this query :{self.userQuery} specifically for this {self.state["metaData"]} and return false if not")
        
        if approve.raw.upper() == "TRUE": 
            print("ENTERED THE TRUE CASE")
            return True
        elif approve.raw.upper() == "FALSE" : 
            print("ENTERED THE FALSE CASE")
            return False




    @listen(analyse) ## if the code was approved
    def executor(self): #no LLM, just deterministic

        with open(self.eventLogPath, 'r') as file:
            eventLogData = file.read()

        globalVariables = {"data" : eventLogData}

        localVariables = {}
        
        exec(self.state["analyseResult"].raw, globalVariables, localVariables)

        self.state["executorArtifacts"] = localVariables["execResults"] ## needed for report agent



    @listen(executor)
    def report(self): #Agent with LLM

        reporter = Agent(
            role="Reporter",
            goal= f"Report the results: {self.state["executorArtifacts"]} for the query:{self.userQuery}",
            backstory="You are the reporter that reports the results in a understandable way for the user.",
            verbose=True
            )

        finalReport = reporter.kickoff(f"Give me a report about the results about my query {self.userQuery}")
    
        return finalReport




flow = pmAnalytics()
flow.plot()
result = flow.kickoff()

print(f"Generated report: {result}")